version: "3.8"

services:
  db_employee:
    image: postgres:16-alpine 
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    container_name: db_employee
    volumes:
      - ./db_proyect:/docker-entrypoint-initdb.d
      - ./db_proyect/pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  db_manager:
    container_name: db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db_proyect/db_manager:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      - db_employee
    restart: unless-stopped
  app_publication:
    build: 
      context: ./proyect-employee
      dockerfile: Dockerfile
    env_file:
      - .env

    container_name: app_publication
    volumes:
      - ./proyect-employee/.:/usr/src
      - /usr/src/node_modules
    depends_on:
      - db_employee
    ports:
      - "3000:3000"  