version: "3.8"

services:
  db_employee:
    image: postgres:16-alpine 
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    container_name: db_employee
    volumes:
      - ./db_proyect:/docker-entrypoint-initdb.d
      - ./db_proyect/pg_data:/var/lib/postgresql/data:rw
    networks:
      - net_prod
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 180M
        reservations:
          cpus: "0.1"
          memory: 128M
  db_manager:
    container_name: db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db_proyect/db_manager:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - net_prod
    depends_on:
      - db_employee
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 220M
        reservations:
          cpus: "0.1"
          memory: 128M
  app_publication:
    build: 
      context: ./proyect-employee
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app_publication
    volumes:
      - /usr/src/node_modules
    networks:
      - net_prod
    depends_on:
      - db_employee
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 250M
        reservations:
          cpus: "0.1"
          memory: 128M
  
networks:
  net_prod:
    driver: bridge
    driver_opts:
      com.docker.netwwork.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - 
        subnet: 192.168.0.1/24
        gateway: 192.168.0.1
      -
        subnet: "2001:0db8:85a3:0000:0000:8a2e:0370:7334/64"
        gateway: "2001:0db8:85a3::1"