version: "3.8"

services:
  db_employee:
    image: postgres:16-alpine 
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
    container_name: db_employee
    volumes:
      - ./db_proyect:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  db_manager:
    container_name: db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db/db_manager:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      - db_employee
    restart: unless-stopped
  app_publication:
    build: 
      context: ./proyect-employee
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_SECRET=${JWT_SECRET}
      - PAGE_NUMBER=${PAGE_NUMBER}
      - PAGE_SIZE=${PAGE_SIZE}
      - USER_ADMIN=${USER_ADMIN}
      - PASS_ADMIN=${PASS_ADMIN}

    container_name: app_publication
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run start:dev
    depends_on:
      - db_employee
    ports:
      - "3000:3000"  
  